version: "3"
services: 
    # mysql5.7
    mysql57: 
        image: mysql:5.7
        container_name: mysql57
        restart: always
        volumes: 
            - ./data/mysql57:/var/lib/mysql
        ports: 
            - 3306:3306
        environment: 
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=root
    
    # redis
    redis: 
        image: redis:latest
        container_name: redis
        restart: always
        ports: 
            - 6379:6379
networks: 
    default: 
        external: true
        name: default-network

